### ISSUE TITLE
Use Bull job statuses to determine run completion

### ISSUE THREAD

**Issue by tokebe** [biothings/bte-auto-demos#14]
Currently, when displaying the `/demotests` route, the server opens, reads, and parses *every* summary file to determine run completion. This is obviously *very* inefficient. 

Thankfully, each run is scheduled through Bull, so we could instead just check that the Bull job is completed by getting its status. The jobID is `demotests:${runStamp}`, so it should be fairly convenient to get the appropriate job.

**Comment by rjawesome** [comment]
Working on this
