### ISSUE TITLE
Improved response checking for TRAPI 1.4

### ISSUE THREAD

**Issue by tokebe** [biothings/bte-auto-demos#24]
With TRAPI 1.4, we want to improve the sanity checks we're doing on the response structure and contents.

I've made a script which I was using during subclassing development to check responses, it should be considered the minimum of additions we'd want for this:

[bte-sanity-check.txt](https://github.com/biothings/bte-auto-demos/files/11727463/bte-sanity-check.txt)

**Comment by tokebe** [comment]
@rjawesome Assigning you to this, no rush if you have other priorities.

**Comment by rjawesome** [comment]
I have started on ``new-sanity-checks`` branch.
