### ISSUE TITLE
General refactor and cleaning

### ISSUE THREAD

**Issue by tokebe** [biothings/bte-auto-demos#6]
This server was put together quite hastily and as such only has a bare minimum of organization and formatting. A refactor to make the workflow more straightforward and the files easier to navigate is in order. Some files might benefit from having certain functions split off into new files, etc.

**Comment by rjawesome** [comment]
I was wondering if it would be a good idea to migrate to typescript along with a general refactor?

**Comment by tokebe** [comment]
Because this server is largely a development testing platform, and not meant to be used in production circumstances, I see the benefits from typescript as outweighed by the cost to rapid prototyping that it imposes. I don't think we should migrate to typescript.

**Comment by tokebe** [comment]
Closing issue as it's simply not a high enough priority.
